# Generated by Django 4.1.7 on 2023-03-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_cuny_alter_userprofile_cuny'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
