# Generated by Django 4.1.7 on 2023-03-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
